import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
	weight: ["400", "600"],
	style: ["normal"],
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<div className="min-h-screen w-full flex flex-col justify-between">
					<Navbar />
					<div className="min-h-screen md:h-full w-full flex flex-col justify-start">
						{children}
					</div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
